version: "3.7"
services:
  app:
    build:
      args:
        user: docker-project-user
        uid: 10000
      context: ./
      dockerfile: Dockerfile
    image: docker-project
    container_name: docker-project-app
    restart: unless-stopped
    working_dir: /var/www/

  nginx:
    image: nginx:alpine
    container_name: docker-project-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/:rw
      - ./docker-compose/nginx:/etc/nginx/conf.d/:ro
